# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift
run-name: ${{ github.actor }} está testando as suas ações
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - run: echo "corinthians"
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
